import Link from 'next/link'

const SECTIONS = [
  { id:'terms', title:'Terms of Service', content:[
    { h:'Acceptance', t:'By accessing PrivaScan or using the API, you agree to these terms. If you disagree with any part, do not use the service.' },
    { h:'Nature of Service', t:'PrivaScan provides automated risk analysis of EVM smart contracts for informational purposes only. Scores are generated by automated systems and are not audits, certifications, or endorsements. They may be incomplete, inaccurate, or out of date.' },
    { h:'Not Financial or Legal Advice', t:'Nothing on PrivaScan — including scores, grades, reports, or written content — constitutes financial advice, investment advice, legal advice, or a recommendation to buy, sell, or interact with any asset or protocol. Always conduct your own research and consult qualified advisors.' },
    { h:'API Usage', t:'API keys are issued for personal and commercial use. You may not resell access to the API, use it to build a competing service without disclosure, or abuse rate limits through key sharing. We reserve the right to suspend or revoke any API key at any time.' },
    { h:'Accuracy and Liability', t:'PrivaScan makes no warranties about the accuracy, completeness, or fitness for purpose of any score or data. We are not liable for any loss or damage resulting from reliance on PrivaScan output, including losses from interacting with smart contracts based on our scores.' },
    { h:'Changes to Terms', t:'We may update these terms at any time. Continued use of PrivaScan after changes constitutes acceptance. Material changes will be announced on Twitter/X @privascan.' },
  ]},
  { id:'disclaimer', title:'Disclaimer', content:[
    { h:'Informational Only', t:'PrivaScan is a research and risk awareness tool. A grade A score does not mean a contract is safe. A grade F score does not mean a contract is malicious. Use scores as one input among many in your own due diligence process.' },
    { h:'OFAC Screening', t:'OFAC screening is automated against the consolidated SDN list. It is not a legal compliance determination. Consult legal counsel for regulatory compliance decisions.' },
    { h:'Slither Analysis', t:'Slither static analysis may produce false positives and may miss certain vulnerability classes. It is not a substitute for a professional smart contract audit.' },
  ]},
]

export default function LegalPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 pt-28 pb-16">
      <Link href="/" className="font-mono text-xs text-slate-500 hover:text-slate-300 transition-colors inline-flex items-center gap-2 mb-8 cursor-pointer">← HOME</Link>
      <div className="mb-10">
        <div className="font-mono text-xs tracking-widest mb-3" style={{ color: '#00d4ff' }}>// LEGAL</div>
        <h1 className="font-orbitron font-black text-white mb-2" style={{ fontSize: 'clamp(2rem,5vw,3rem)' }}>
          Legal
        </h1>
        <p className="font-mono text-xs text-slate-500">Last updated: May 2026</p>
      </div>
      {SECTIONS.map(s => (
        <div key={s.id} id={s.id} className="glass rounded-xl p-8 mb-6">
          <h2 className="font-orbitron text-xl font-bold text-white mb-6">{s.title}</h2>
          <div className="space-y-5">
            {s.content.map((c,i) => (
              <div key={i}>
                <div className="font-orbitron text-sm font-bold mb-2" style={{ color: '#00d4ff' }}>{c.h}</div>
                <p className="font-mono text-sm text-slate-400 leading-relaxed">{c.t}</p>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  )
}
